image: maven:3.8.1-openjdk-17

pipelines:
  default:
    - step:
        name: Build Dependencies and Migrate Database
        caches:
          - maven
        services:
          - postgres
        script:
          - mvn clean install -DskipTests
          - cd springboot-personal-migration/
          - mvn flyway:migrate -P flyway
          - mvn spring-boot:run
        after-script:
          # Collect checkstyle results, if any, and convert to Bitbucket Code Insights.
          - pipe: atlassian/checkstyle-report:0.3.0
    - step:
        name: Unit Test/Integration Test
        caches:
          - maven
        services:
          - postgres
        script:
          - mvn test
        after-script:
          # Collect checkstyle results, if any, and convert to Bitbucket Code Insights.
          - pipe: atlassian/checkstyle-report:0.3.0
    - step:
        name: Security Scan
        caches:
          - maven
        services:
          - postgres
        script:
          # Run a security scan for sensitive data.
          # See more security tools at https://bitbucket.org/product/features/pipelines/integrations?&category=security
          - pipe: atlassian/git-secrets-scan:0.5.1
    - step:
        name: Drop All Databases
        image: postgres:13
        services:
          - postgres
        script:
          - psql -h localhost -U postgres -c "DROP DATABASE IF EXISTS chart_tick;"

definitions:
  caches:
    maven: ~/.m2/repository

  services:
    postgres:
      image: postgres:13
      environment:
        POSTGRES_DB: 'chart-tick'
        POSTGRES_USER: 'postgres'
        POSTGRES_PASSWORD: 'postgres'