image: maven:3.8.1-openjdk-17

pipelines:
  default:
    - step:
        name: Build Dependencies and Integration Testing
        caches:
          - maven
        services:
          - postgres
        script:
          - mvn clean install -DskipTests
          - cd springboot-personal-migration/
          - mvn flyway:migrate -P flyway
          - cd ../
          - mvn test
    - step:
          name: Sonar Analysis
          caches:
            - maven
          services:
            - postgres
          script:
            - mvn clean install
            - mvn verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=spring-personal-framework_spring-personal-framework
    - step:
        name: Security Scan
        caches:
          - maven
        script:
          # Run a security scan for sensitive data.
          # See more security tools at https://bitbucket.org/product/features/pipelines/integrations?&category=security
          - pipe: atlassian/git-secrets-scan:0.5.1
    - step:
        name: Drop All Database After Scanning and Testing
        image: postgres:13
        services:
          - postgres
        script:
          - psql -h localhost -U postgres -c "DROP DATABASE IF EXISTS chart_tick;"

definitions:
  caches:
    maven: ~/.m2/repository

  services:
    postgres:
      image: postgres:13
      environment:
        POSTGRES_DB: 'chart-tick'
        POSTGRES_USER: 'postgres'
        POSTGRES_PASSWORD: 'postgres'